on:
  push:
    branches:
      - master
jobs:
  stats_daily:
    runs-on: ubuntu-latest
    name: Build docker images
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set SINCE env
        run: echo "SINCE=$(date -d "yesterday 0" -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
      - name: Set UNTIL env
        run: echo "UNTIL=$(date -d "today 0" -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username cymruu --password-stdin
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Generate docker-export tags
        id: docker-export-tags
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/cymruu/amw-stats/docker-export
      -
        name: Build docker-export
        uses: docker/build-push-action@v3
        with:
          context: docker-export
          tags: ${{ steps.docker-export-tags.outputs.tags }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Generate docker-stats tags
        id: docker-stats-tags
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/cymruu/amw-stats/docker-stats
      -
        name: Build docker-stats
        uses: docker/build-push-action@v3
        with:
          context: ./docker-stats
          tags: ${{ steps.docker-stats-tags.outputs.tags }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Generate docker-imagemagick tags
        id: docker-imagemagick-tags
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/cymruu/amw-stats/docker-imagemagick
      -
        name: Build docker-imagemagick
        uses: docker/build-push-action@v3
        with:
          context: docker-imagemagick
          tags: ${{ steps.docker-imagemagick-tags.outputs.tags }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Generate docker-post tags
        id: docker-post-tags
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/cymruu/amw-stats/docker-post
      -
        name: Build docker-post
        uses: docker/build-push-action@v3
        with:
          context: docker-post
          tags: ${{ steps.docker-post-tags.outputs.tags }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
