on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 6 * * *'
jobs:
  stats_daily:
    runs-on: ubuntu-latest
    name: Trigger daily stats generation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set SINCE env
        run: echo "SINCE=$(date -d "yesterday 0" -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
      - name: Set UNTIL env
        run: echo "UNTIL=$(date -d "today 0" -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
      - run: docker build -t docker-export docker-export
      - name: Build docker-stats
        uses: docker/build-push-action@v3
        with:
          load: true
          context: docker-stats
          tags: docker-stats
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: docker build -t docker-imagemagick docker-imagemagick 
      - run: docker build -t docker-post docker-post 
      - name: Generate stats
        run: ./docker.sh
        env:
          SINCE: ${{ env.SINCE }}
          UNTIL: ${{ env.UNTIL }}
          PERIOD: "daily"
          AMW_STATS_MONGO_HOST: ${{ secrets.AMW_STATS_MONGO_HOST }}
          ACCOUNT_KEY: ${{ secrets.ACCOUNT_KEY }}
          APPKEY: ${{ secrets.APPKEY }}
          SECRET: ${{ secrets.SECRET }}
