on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
  push:
jobs:
  stats_daily:
    runs-on: ubuntu-latest
    name: Trigger daily stats generation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set TZ env
        run: echo "TZ=Europe/Warsaw" >> $GITHUB_ENV
      - name: Set SINCE env
        run: echo "SINCE=$(date -d "yesterday 0" --iso-8601=seconds)" >> $GITHUB_ENV
      - name: Set UNTIL env
        run: echo "UNTIL=$(date -d "today 0" --iso-8601=seconds)" >> $GITHUB_ENV
      - name: Build docker export
        run: docker build -t docker-export docker-export
      - name: Build docker-stats
        run: docker build -t docker-stats docker-stats
      - name: Build docker-imagemagick
        run: docker build -t docker-imagemagick docker-imagemagick
      - name: Build docker-post
        run: docker build -t docker-post docker-post
      - name: Export data
        run: docker run --rm
          -e AMW_STATS_MONGO_HOST
          -e SINCE
          -e UNTIL
          -v $(pwd)/exported:/workspace/exported
          docker-export
        env:
          AMW_STATS_MONGO_HOST: ${{ secrets.AMW_STATS_MONGO_HOST }}
          SINCE: ${{ env.SINCE }}
          UNTIL: ${{ env.UNTIL }}
      - name: Generate stats
        run: docker run --user root --rm
          -e SINCE
          -e UNTIL
          -e PERIOD
          -v $(pwd)/exported:/workspace/exported
          -v $(pwd)/results:/workspace/pandas/results
          docker-stats
        env:
          SINCE: ${{ env.SINCE }}
          UNTIL: ${{ env.UNTIL }}
          PERIOD: "daily"
      - name: Merge generated charts into one
        run: docker run --rm
          -v $(pwd)/results:/results
          docker-imagemagick
      - name: Publish stats
        run: docker run --rm
          -v $(pwd)/results:/results
          -e APPKEY
          -e SECRET
          -e ACCOUNT_KEY
          docker-post
        env:
          APPKEY: ${{ secrets.APPKEY }}
          SECRET: ${{ secrets.SECRET }}
          ACCOUNT_KEY: ${{ secrets.ACCOUNT_KEY }}
